services:
    server:
        build:
            context: .
        command: ["yarn", "debug"]
        ports:
            - "3000:3000"
            - "9229:9229"
        environment:
            - datastores__acl__url=mongodb://mongo
            - datastores__mongo__url=mongodb://mongo
            - NODE_ENV=production
        links:
            - mongo
    mongo:
        image: mongo