services:
    nginx:
        # For brotli support, replace with: ghcr.io/macbre/nginx-http3:latest
        image: nginx:alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - server
    server:
        build:
            context: .
        environment:
            - datastores__acl__url=mongodb://mongo
            - datastores__cache__type=redis
            - datastores__cache__url=redis://redis
            - datastores__events__type=redis
            - datastores__events__url=redis://redis
            - datastores__logs__type=redis
            - datastores__logs__url=redis://redis
            - datastores__mongo__url=mongodb://mongo
            - NODE_ENV=production
        depends_on:
            - redis
            - mongo
    redis:
        image: redis
    mongo:
        image: mongo
