---
apiVersion: v1
kind: Service
metadata:
  name: petstore-services
  labels:
    app.kubernetes.io/instance: petstore-services
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: nodejs
      protocol: TCP
  selector:
    app.kubernetes.io/instance: petstore-services