---
kind: ConfigMap
apiVersion: v1
metadata:
  name: service-config
data:
  cookie_secret: {{ tpl $.Values.cookies.secret . | quote }}
  session__secret: {{ tpl $.Values.sessions.secret . | quote }}
  NODE_ENV: "{{ $.Values.environment }}"
  {{- $corsHosts := list "http://localhost:3000" $.Values.host }}
  cors__origins: {{ $corsHosts | toJson | quote }}
  {{- range $k, $v := $.Values.service.config }}
  {{- if kindIs "string" $v }}
  {{ $k }}: {{ tpl $v $ | quote }}
  {{- else if kindIs "slice" $v }}
  {{ $k }}: {{ $v | toJson | quote }}
  {{- else if kindIs "map" $v }}
  {{ $k }}: {{ $v | toJson | quote }}
  {{- else }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: service-db-info
type: Opaque
data:
  datastores__acl__database: {{ include "rrst.render" (dict "value" $.Values.service.mongodb.acl.name "context" $) | b64enc | quote }}
  {{- if $.Values.mongodb.create }}
  datastores__acl__host: {{ include "rrst.render" (dict "value" $.Values.service.mongodb.acl.host "context" $) | default (printf "%s" $.Values.mongodb.fullnameOverride) | b64enc | quote }}
  {{- end }}
  datastores__acl__type: {{ print "mongodb" | b64enc | quote }}
  {{- if $.Values.mongodb.url }}
  datastores__acl__url: {{ (include "rrst.render" (dict "value" $.Values.mongodb.url "context" $) | b64enc | quote) }}
  {{- else if $.Values.service.mongodb.acl.url }}
  datastores__acl__url: {{ (include "rrst.render" (dict "value" $.Values.service.mongodb.acl.url "context" $) | b64enc | quote) }}
  {{- end }}
  datastores__mongo__database: {{ include "rrst.render" (dict "value" $.Values.service.mongodb.mongo.name "context" $) | b64enc | quote }}
  {{- if $.Values.mongodb.create }}
  datastores__mongo__host: {{ include "rrst.render" (dict "value" $.Values.service.mongodb.mongo.host "context" $) | default (printf "%s" $.Values.mongodb.fullnameOverride) | b64enc | quote }}
  {{- end }}
  datastores__mongo__type: {{ print "mongodb" | b64enc | quote }}
  {{- if $.Values.mongodb.url }}
  datastores__mongo__url: {{ include "rrst.render" (dict "value" $.Values.mongodb.url "context" $) | b64enc | quote }}
  {{- else if $.Values.service.mongodb.mongo.url }}
  datastores__mongo__url: {{ include "rrst.render" (dict "value" $.Values.service.mongodb.mongo.url "context" $) | b64enc | quote }}
  {{- end }}