host: localhost
environment: dev
auth:
  audience: '{{ .Values.host }}'
  issuer: 'api.{{ .Values.host }}'
  expiresIn: 1 hour
  secret: '{{ randAlphaNum 32 }}'
cookies:
  secret: '{{ randAlphaNum 32 }}'
sessions:
  secret: '{{ randAlphaNum 32 }}'
common:
  storageClass: default
  logs:
    level: info
gateway:
  name: api-gateway
  namespace: '{{ .Release.Namespace }}'
  hsts: true
  tls: true
redis:
  create: true
  url: 'redis://db-redis-master'
  architecture: standalone
  auth:
    enabled: false
  fullnameOverride: db-redis
  usePassword: false
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
  networkPolicy:
    enabled: true
    allowExternal: false
mongodb:
  create: true
  architecture: standalone
  fullnameOverride: mongodb
  auth:
    enabled: false
service:
  image:
    registry: ghcr.io
    repository: rapidrest/petstore
    tag: 1.1.0
  replicas: 1
  mongodb:
    acl:
      name: access_control_lists
      host: ''
    mongo:
      name: petstore
      fullnameOverride: ''
      host: ''
  config:
    logs: true
    metrics: true
    releaseNotes: true
