name: CI

on:
  push:
    branches: [ ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Cache node_modules, dist, docs
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            dist
            docs
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      #- name: Build
      #  run: yarn docs

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    container:
      image: node:lts-bookworm
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: junit.xml

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build test
        run: |
          docker build -t ${{ github.event.repository.name }} . --no-cache
          docker rmi ${{ github.event.repository.name }}

  test-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Run Lint
        run: helm lint ./helm

  test-run:
    runs-on: ubuntu-latest
    needs: test-docker-build
    steps:
      - uses: actions/checkout@v4
      - name: Run test-run.sh
        run: bash ./test-run.sh

  validate:
    runs-on: ubuntu-latest
    container:
      image: node:lts-bookworm
    needs: build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Run validation script
        run: |
          set +e
          bash ./validate.sh
